spring.application.name=Application
server.port=8080

# Default to MySql if no profile is selected
# see appli cation-mysql.properties
spring.profiles.active=h2
#spring.profiles.active=mysql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.results=trace